apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-svc        # e.g., nodejs-app-svc
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}   # LoadBalancer (external) or ClusterIP (internal)
  selector:
    app: {{ .Chart.Name }}
  ports:
    - port: {{ .Values.service.port }}       # Exposed port
      targetPort: {{ .Values.containerPort }} # Internal container port
